language: c
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'deb http://en.archive.ubuntu.com/ubuntu/ artful main universe'
    packages:
      - e2fsprogs
      - python-pytest
      - python-keyutils

install:
  - sudo make travis-install

script:
  - sudo make travis-script
